spring.application.name=java-spring-ai
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n



spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=openai/gpt-oss-20b:free
spring.ai.openai.base-url=https://openrouter.ai/api

#spring.ai.ollama.chat.options.model=llama3.2
#spring.ai.chat.client.enabled=false
#logging.level.org.springframework.ai.chat.client.advisor=DEBUG